"""add telegram_id to users

Revision ID: add_telegram_id
Revises: e06eb85f8aa8
Create Date: 2025-01-07 17:20:00.000000

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "add_telegram_id"
down_revision: Union[str, None] = "e06eb85f8aa8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("telegram_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_column("users", "telegram_id")
    # ### end Alembic commands ###
