"""fix goal type

Revision ID: fix_goal_type
Revises: telegram_only_users
Create Date: 2025-01-07 19:00:00.000000

"""

from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fix_goal_type"
down_revision: Union[str, None] = "telegram_only_users"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Изменяем тип поля goal в profiles с enum на VARCHAR
    op.execute("ALTER TABLE profiles ALTER COLUMN goal TYPE VARCHAR(50)")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Возвращаем обратно к enum (если нужно)
    # op.execute("ALTER TABLE profiles ALTER COLUMN goal TYPE goal_enum
    # USING goal::goal_enum")
    pass

    # ### end Alembic commands ###
