"""telegram only users

Revision ID: telegram_only_users
Revises: b97475dc6cb6
Create Date: 2025-01-07 18:00:00.000000

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "telegram_only_users"
down_revision: Union[str, None] = "b97475dc6cb6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Делаем email необязательным
    op.alter_column("users", "email", nullable=True)

    # Делаем hashed_password необязательным
    op.alter_column("users", "hashed_password", nullable=True)

    # Делаем telegram_id обязательным (не NULL)
    op.alter_column("users", "telegram_id", nullable=False)

    # Добавляем новые поля для Telegram данных
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "users", sa.Column("last_name", sa.String(length=100), nullable=True)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Убираем новые поля
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")

    # Возвращаем обязательность полей
    op.alter_column("users", "telegram_id", nullable=True)
    op.alter_column("users", "hashed_password", nullable=False)
    op.alter_column("users", "email", nullable=False)

    # ### end Alembic commands ###
